name: Test

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.25.4

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

  test:
    needs: check

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.25.4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8.1

      - name: Set PATH
        run: julia -e 'joinpath(homedir(), ".deno", "bin")' >> $GITHUB_PATH

      - name: Install dependencies
        run: julia test/addpkgs.jl

      - name: Test
        run: julia test/runtests.jl
